services:
  - type: web
    name: migrantconnect
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:8000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
